version: '3.8'

services:

 webserver:
  build:
   context: ./php
   dockerfile: dockerfile
  ports:
   - 1121:80
  depends_on:
   - db

 db:
  image: mariadb
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test_db

 phpmyadmin:
  image: phpmyadmin
  links:
   - db
  depends_on:
   - db
  ports:
   - 1123:80
  environment:
    PMA_HOST: db
    PMA_PORT: 3306
