FROM php:7.4-apache
ENV MYSQL_NAME=$MYSQL_NAME \
    MYSQL_USER=$MYSQL_USER \
    MYSQL_PASSWORD=$MYSQL_PASSWORD \
    MYSQL_DATABASE=$MYSQL_DATABASE \ 
    EXTERNAL_SQL_PORT=$EXTERNAL_SQL_PORT
RUN apt-get update && apt-get upgrade -y &&\
    docker-php-ext-install mysqli &&\
    env
COPY ./www /var/www/html
EXPOSE 80
